"""Smallest certifiable alpha (spec section 8.6) with the real Calibrate sizes from splits/splits_v1.json.

With n kept Calibrate shots and e errors among them, a threshold is certified at level alpha when the
binomial p-value P(Bin(n, alpha) <= e) is at most delta. The smallest such alpha is the one-sided
(1 - delta) Clopper-Pearson upper bound; with e = 0 it is 1 - delta^(1/n), about 3/n at delta = 0.05.

    python scripts/alpha_floor.py
Writes results/alpha_floor.md.
"""
import collections
import json
import pathlib

from scipy.stats import beta

REPO = pathlib.Path(__file__).resolve().parents[1]
DELTA = 0.05
TRUE_R = 1e-3


def upper(n, e, delta=DELTA):
    return 1.0 if e >= n else float(beta.ppf(1 - delta, e + 1, n - e))


def main():
    m = json.loads((REPO / "splits" / "splits_v1.json").read_text())
    cal = {k: v.get("calibrate", 0) for k, v in m["experiments"].items()}
    per_exp = sorted({c for c in cal.values() if c})
    pools = collections.defaultdict(int)          # (distance, rounds) -> pooled calibrate shots over patches, bases
    count = collections.Counter()
    for k, c in cal.items():
        if c:
            d = int(k[1:k.index("_")])
            r = int(k.rsplit("/r", 1)[1])
            pools[(d, r)] += c
            count[(d, r)] += 1

    rows = []
    for n in per_exp:
        rows.append(("One experiment, keep all", n))
        rows.append(("One experiment, keep 50%", n // 2))
    for d in (3, 5, 7):
        for k, nn in sorted({(count[key], pools[key]) for key in pools if key[0] == d}):
            rows.append((f"d={d}, one round count, {k} patch-basis experiments pooled, keep all", nn))

    lines = ["# Smallest certifiable alpha (generated by scripts/alpha_floor.py)", "",
             f"delta = {DELTA}; Calibrate sizes from `splits/splits_v1.json` (r=13 has no Calibrate shots).", "",
             f"| Setting | Kept Calibrate shots n | Smallest alpha, 0 errors | Smallest alpha if true R = {TRUE_R:g} |",
             "|---|---|---|---|"]
    for name, n in rows:
        e = round(n * TRUE_R)
        lines.append(f"| {name} | {n:,} | {upper(n, 0):.1e} | {upper(n, e):.1e} |")
    lines += ["", "Pooling assumes the pooled experiments are exchangeable, which is what RQ3 tests; "
              "report pooled guarantees only with that assumption stated."]
    out = REPO / "results" / "alpha_floor.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
