"""Two checks on the Willow archive before any modelling (spec section 14, items 5 and M1 prep).

1. Logical-gap precondition (spec 8.3): in every DEM we might decode with, each error component that flips
   the observable must touch at most one real detector. Checked on the SI1000 DEM built from
   circuit_noisy_si1000.stim and on every error_model.dem shipped under decoding_results/.
2. Google's own decoder results: logical error fraction (predicted XOR actual) per pathway, averaged over
   patches and bases, for a few round counts. These are the numbers our loader + decoders must reproduce.

Usage:
    python scripts/data_checks.py data/raw/google_105Q_surface_code_d3_d5_d7.zip
Writes docs/data_checks.md.
"""
import argparse
import collections
import hashlib
import pathlib
import re
import sys
import zipfile

import numpy as np
import stim

CONFIG_RE = re.compile(r"(?P<d>d\d+)_at_(?P<patch>q\d+_\d+)/(?P<basis>[XZ])/r(?P<rounds>\d+)/")
REPO = pathlib.Path(__file__).resolve().parents[1]
SHOW_ROUNDS = (10, 50, 130, 250)


def gap_precondition(dem):
    """(observable-flipping components, components touching more than one detector)."""
    total = bad = 0
    for inst in dem.flattened():
        if inst.type != "error":
            continue
        parts = [[]]
        for t in inst.targets_copy():
            if t.is_separator():
                parts.append([])
            else:
                parts[-1].append(t)
        for p in parts:
            if any(t.is_logical_observable_id() for t in p):
                total += 1
                bad += sum(t.is_relative_detector_id() for t in p) > 1
    return total, bad


def obs_bits(raw):
    """One observable per shot in b8 format: one byte per shot, bit 0 holds the flip."""
    return np.frombuffer(raw, dtype=np.uint8) & 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("zip", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=REPO / "docs" / "data_checks.md")
    args = ap.parse_args()
    zf = zipfile.ZipFile(args.zip)
    names = zf.namelist()

    exps = sorted({m.group(0) for n in names if (m := CONFIG_RE.search(n))})
    prefix = {e: next(n for n in names if e in n).split(e)[0] + e for e in exps}
    print(f"{len(exps)} experiment directories")

    pre = collections.defaultdict(lambda: [0, 0, 0])      # source -> [dems checked, obs components, bad]
    seen = {}
    ler = collections.defaultdict(list)                   # (pathway, d, r) -> list of error fractions
    for k, e in enumerate(exps):
        m = CONFIG_RE.search(e)
        d, r = int(m["d"][1:]), int(m["rounds"])
        base = prefix[e]
        noisy = stim.Circuit(zf.read(base + "circuit_noisy_si1000.stim").decode())
        sources = {"SI1000 DEM from circuit_noisy_si1000.stim": noisy.detector_error_model(decompose_errors=True)}
        actual = obs_bits(zf.read(base + "obs_flips_actual.b8"))
        for n in names:
            if n.startswith(base + "decoding_results/") and n.endswith("/error_model.dem"):
                pw = n.split("/decoding_results/")[1].split("/")[0]
                text = zf.read(n)
                h = hashlib.sha1(text).hexdigest()
                if h not in seen:
                    seen[h] = stim.DetectorErrorModel(text.decode())
                    sources[f"shipped DEM ({pw.split('_with_')[-1]})"] = seen[h]
                pred = obs_bits(zf.read(n.replace("error_model.dem", "obs_flips_predicted.b8")))
                ler[(pw, d, r)].append(float(np.mean(pred != actual)))
        for src, dem in sources.items():
            tot, bad = gap_precondition(dem)
            pre[src][0] += 1
            pre[src][1] += tot
            pre[src][2] += bad
        if (k + 1) % 50 == 0:
            print(f"  {k + 1}/{len(exps)}", flush=True)

    lines = ["# Data checks (generated by scripts/data_checks.py)", "",
             "## Logical-gap precondition", "",
             "Each error component that flips the observable must touch at most one detector (spec section 8.3).", "",
             "| DEM source | Distinct DEMs checked | Observable-flipping components | Components violating |",
             "|---|---|---|---|"]
    for src, (n, tot, bad) in sorted(pre.items()):
        lines.append(f"| {src} | {n} | {tot:,} | {bad:,} |")
    verdict = "holds" if all(b == 0 for _, _, b in pre.values()) else "FAILS for at least one source"
    lines += ["", f"Verdict: the precondition {verdict}.", "",
              "## Google's decoder results (logical error fraction, mean over patches and bases)", ""]
    pws = sorted({p for p, _, _ in ler})
    lines += ["| Pathway | d | " + " | ".join(f"r={r}" for r in SHOW_ROUNDS) + " |",
              "|---|---|" + "---|" * len(SHOW_ROUNDS)]
    for p in pws:
        for d in (3, 5, 7):
            cells = [f"{np.mean(ler[(p, d, r)]):.4f}" if ler.get((p, d, r)) else "-" for r in SHOW_ROUNDS]
            lines.append(f"| `{p}` | {d} | " + " | ".join(cells) + " |")
    lines += ["", "Error fraction = share of shots where `obs_flips_predicted` differs from `obs_flips_actual`."]
    args.out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    sys.exit(main())
