"""Summarise results/m1_baselines.csv: per-cycle logical error, Lambda, agreement with Google, and two figures.

Per-cycle error: for each (decoder, distance, patch, basis), fit log(1 - 2 P_L(r)) = log A + r log(1 - 2 eps)
by weighted least squares over r >= 10, excluding r = 13 (held out: the RL prior was fitted on it).
Weights are the inverse binomial variance of log(1 - 2 P); points with P >= 0.45 are dropped.
eps per distance is the mean over patch-basis fits; Lambda_{d/d+2} = eps_d / eps_{d+2}.

    python scripts/m1_summary.py
Writes results/m1_summary.md, results/m1_ler_vs_rounds.png, results/m1_eps_vs_distance.png.
"""
import collections
import csv
import pathlib

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from qeccal import plotting  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RES = REPO / "results"
FIT_MIN_ROUNDS, EXCLUDE_ROUNDS, P_MAX = 10, {13}, 0.45

LABEL = {
    ("ours", "pymatching"): "PyMatching (ours)",
    ("ours", "pymatching_correlated"): "PyMatching, correlated (ours)",
    ("google", "correlated_matching"): "Correlated matching (Google)",
    ("google", "harmony"): "Harmony (Google)",
    ("google", "libra"): "Libra (Google)",
}
ORDER = list(LABEL)
PLOT = ORDER[:3] + [ORDER[4]]          # four series, the palette's four slots; Harmony is in the tables


def load():
    with (RES / "m1_baselines.csv").open() as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        for k in ("distance", "rounds", "shots", "errors", "test_shots", "test_errors"):
            r[k] = int(r[k])
    return rows


def fit_eps(points):
    """points: list of (rounds, errors, shots). Returns eps per cycle or nan."""
    r, y, w = [], [], []
    for rounds, err, n in points:
        p = err / n
        if rounds < FIT_MIN_ROUNDS or rounds in EXCLUDE_ROUNDS or p >= P_MAX or err == 0:
            continue
        r.append(rounds)
        y.append(np.log(1 - 2 * p))
        w.append(1 / ((2 / (1 - 2 * p)) ** 2 * p * (1 - p) / n))
    if len(r) < 3:
        return float("nan")
    X = np.column_stack([np.ones(len(r)), r])
    W = np.diag(w)
    beta = np.linalg.solve(X.T @ W @ X, X.T @ W @ np.array(y))
    return (1 - np.exp(beta[1])) / 2


def main():
    rows = load()
    groups = collections.defaultdict(list)
    for r in rows:
        groups[(r["source"], r["decoder"], r["prior"], r["distance"], r["patch"], r["basis"])].append(
            (r["rounds"], r["errors"], r["shots"]))
    eps = collections.defaultdict(list)       # (source, decoder, prior, d) -> eps of each patch-basis
    for (src, dec, prior, d, patch, basis), pts in groups.items():
        e = fit_eps(pts)
        if np.isfinite(e):
            eps[(src, dec, prior, d)].append(e)

    n_exp = len({r["key"] for r in rows})
    lines = ["# M1 baselines (generated by scripts/m1_summary.py)", "",
             f"{n_exp} experiments, all 50,000 shots each. Source: `results/m1_baselines.csv`.", "",
             "## Logical error per cycle", "",
             f"Fit over r >= {FIT_MIN_ROUNDS}, r = 13 excluded, points with P_L >= {P_MAX} dropped; "
             "mean over patch-basis fits, with the range in brackets.", ""]
    for prior in ("si1000", "rl"):
        lines += [f"### Prior: {'SI1000' if prior == 'si1000' else 'RL-optimized'}", "",
                  "| Decoder | eps d=3 (%) | eps d=5 (%) | eps d=7 (%) | Lambda 3/5 | Lambda 5/7 |", "|---|---|---|---|---|---|"]
        for src, dec in ORDER:
            vals = {d: eps.get((src, dec, prior, d), []) for d in (3, 5, 7)}
            if not any(vals.values()):
                continue
            m = {d: np.mean(v) if v else np.nan for d, v in vals.items()}
            cells = [f"{100 * m[d]:.3f} [{100 * min(v):.3f}-{100 * max(v):.3f}]" if v else "-" for d, v in vals.items()]
            lines.append(f"| {LABEL[(src, dec)]} | " + " | ".join(cells) +
                         f" | {m[3] / m[5]:.2f} | {m[5] / m[7]:.2f} |")
        lines.append("")

    agree_rounds = (1, 10, 50, 250)
    lines += ["## Per-shot agreement with Google's correlated matching (same prior)", "",
              "Share of shots where our prediction equals Google's, pooled over patches and bases. At long runs both "
              "decoders are close to coin flips, so agreement falls towards 50% there by construction; the short "
              "runs are the informative check.", "",
              "| Our decoder | Prior | d | " + " | ".join(f"r={r}" for r in agree_rounds) + " |",
              "|---|---|---|" + "---|" * len(agree_rounds)]
    for dec in ("pymatching", "pymatching_correlated"):
        for prior in ("si1000", "rl"):
            for d in (3, 5, 7):
                cells = []
                for rr in agree_rounds:
                    v = [r for r in rows if r["source"] == "ours" and r["decoder"] == dec and r["prior"] == prior
                         and r["distance"] == d and r["rounds"] == rr]
                    cells.append(f"{100 * sum(int(r['agree_with_google_cm']) for r in v) / sum(r['shots'] for r in v):.2f}%"
                                 if v else "-")
                lines.append(f"| {LABEL[('ours', dec)]} | {prior} | {d} | " + " | ".join(cells) + " |")
    lines.append("")
    (RES / "m1_summary.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))

    # --- figures (RL prior) ------------------------------------------------------
    plotting.apply()
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.5), sharey=True)
    for ax, d in zip(axes, (3, 5, 7)):
        for i, (src, dec) in enumerate(PLOT):
            sel = [r for r in rows if r["source"] == src and r["decoder"] == dec and r["prior"] == "rl"
                   and r["distance"] == d and r["rounds"] not in EXCLUDE_ROUNDS]
            agg = collections.defaultdict(lambda: [0, 0])
            for r in sel:
                agg[r["rounds"]][0] += r["errors"]
                agg[r["rounds"]][1] += r["shots"]
            xs = sorted(agg)
            ax.plot(xs, [agg[x][0] / agg[x][1] for x in xs], color=plotting.C[i], marker=plotting.MK[i],
                    markersize=3.5, label=LABEL[(src, dec)])
        ax.set_title(f"d = {d}")
        ax.set_xlabel("QEC rounds")
    axes[0].set_ylabel("Logical error per shot")
    axes[0].set_ylim(0, 0.5)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=4, bbox_to_anchor=(0.5, 1.1))
    fig.savefig(RES / "m1_ler_vs_rounds.png")

    fig, ax = plt.subplots(figsize=(3.8, 2.6))
    for i, (src, dec) in enumerate(PLOT):
        m = [np.mean(eps[(src, dec, "rl", d)]) for d in (3, 5, 7)]
        ax.plot((3, 5, 7), m, color=plotting.C[i], marker=plotting.MK[i],
                label=f"{LABEL[(src, dec)]}, Λ₃/₅ {m[0] / m[1]:.2f}, Λ₅/₇ {m[1] / m[2]:.2f}")
    ax.set_yscale("log")
    ax.set_xticks((3, 5, 7))
    ax.set_xlabel("Code distance")
    ax.set_ylabel("Logical error per cycle")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.2), fontsize=6.5)
    fig.savefig(RES / "m1_eps_vs_distance.png")
    print(f"wrote {RES / 'm1_summary.md'} and two figures")


if __name__ == "__main__":
    main()
