"""M2 summary on the Train split: does postselecting on q reduce logical error, and how calibrated is raw q?

Reads the per-shot cache from scripts/m2_soft_outputs.py. Train split only (spec 8.4): Calibrate and Test
stay untouched until the score functions are frozen in M4. r = 13 has no Train shots and drops out.

    python scripts/m2_summary.py
Writes results/m2_train_metrics.csv (per experiment, method, prior), results/m2_summary.md and three figures.
"""
import collections
import csv
import pathlib

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from qeccal import plotting  # noqa: E402
from qeccal.calibration import brier, ece, error_vs_discard, nll, reliability  # noqa: E402
from qeccal.data import list_experiments, split_indices  # noqa: E402
from qeccal.data.splits import SEED, _key_seed  # noqa: E402
from qeccal.soft.cache import cache_path, load  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RES = REPO / "results"
METHODS = ("mwpm_gap", "exact")
PRIORS = ("si1000", "rl")
DISCARD = (0.0, 0.05, 0.1, 0.2, 0.3, 0.5, 0.7)
NAME = {"mwpm_gap": "MWPM gap", "exact": "Exact posterior"}


def per_experiment():
    rows, pooled = [], collections.defaultdict(lambda: ([], []))
    for e in list_experiments():
        idx = split_indices(e).get("train")
        if idx is None:
            continue
        obs = e.observable_flips()[idx]
        for mi, method in enumerate(METHODS):
            for pi, prior in enumerate(PRIORS):
                if not cache_path(method, prior, e.key).exists():
                    continue
                o = load(method, prior, e.key)
                q, wrong = o["q"][idx], o["pred"][idx] != obs
                rng = np.random.default_rng([SEED, _key_seed(e.key), mi, pi])
                kept, err = error_vs_discard(q, wrong, DISCARD, rng)
                row = {"key": e.key, "distance": e.distance, "patch": e.patch, "basis": e.basis, "rounds": e.rounds,
                       "method": method, "prior": prior, "n": wrong.size, "errors": int(wrong.sum()),
                       "mean_q": float(q.mean()), "ece": ece(q, wrong), "brier": brier(q, wrong), "nll": nll(q, wrong)}
                for f, k, er in zip(DISCARD, kept, err):
                    row[f"kept_{f:.2f}"], row[f"err_{f:.2f}"] = int(k), int(er)
                rows.append(row)
                pooled[(method, prior, e.distance, e.rounds)][0].append(q)
                pooled[(method, prior, e.distance, e.rounds)][1].append(wrong)
    return rows, {k: (np.concatenate(a), np.concatenate(b)) for k, (a, b) in pooled.items()}


def pooled_curve(rows, method, prior, d, r):
    sel = [x for x in rows if x["method"] == method and x["prior"] == prior and x["distance"] == d and x["rounds"] == r]
    if not sel:
        return None
    return {f: sum(x[f"err_{f:.2f}"] for x in sel) / sum(x[f"kept_{f:.2f}"] for x in sel) for f in DISCARD}, sel


def main():
    rows, pooled = per_experiment()
    fields = list(rows[0])
    with (RES / "m2_train_metrics.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    L = ["# M2 soft outputs (generated by scripts/m2_summary.py)", "",
         "Train split only (20,000 shots per experiment); r=13 has no Train shots. Per-shot outputs: "
         "`results/cache/soft/`; per-experiment metrics: `results/m2_train_metrics.csv`.", ""]

    # --- gap predictions vs M1 plain matching (all shots) ----------------------------
    with (RES / "m2_soft_outputs.csv").open() as f:
        soft = [r for r in csv.DictReader(f) if r["method"] == "mwpm_gap"]
    with (RES / "m1_baselines.csv").open() as f:
        m1 = {(r["key"], r["prior"]): int(r["errors"]) for r in csv.DictReader(f)
              if r["source"] == "ours" and r["decoder"] == "pymatching"}
    diffs = [int(r["errors"]) - m1[(r["key"], r["prior"])] for r in soft if (r["key"], r["prior"]) in m1]
    ties = sum(int(r["ties"]) for r in soft)
    L += ["## Check: gap predictions against plain MWPM (M1), all shots", "",
          f"{len(diffs)} experiment-prior pairs. Error counts identical in {sum(d == 0 for d in diffs)}; "
          f"largest difference {max(diffs, key=abs) if diffs else 0} errors in 50,000 shots; "
          f"total difference {sum(diffs)}. Tied shots (gap = 0): {ties}.", ""]

    # --- postselection -----------------------------------------------------------------
    L += ["## Error among kept shots after discarding the most doubtful (MWPM gap)", "",
          "Pooled over patches and bases (sum of errors / sum of kept). Ties broken at random, seed from the split seed.", ""]
    show = (0.0, 0.1, 0.3, 0.5)
    for prior in PRIORS:
        L += [f"### Prior: {'SI1000' if prior == 'si1000' else 'RL-optimized'}", "",
              "| d | r | " + " | ".join(f"discard {int(100 * f)}%" for f in show) + " | shots |", "|---|---|" + "---|" * (len(show) + 1)]
        for d in (3, 5, 7):
            for r in (1, 10, 30, 50):
                res = pooled_curve(rows, "mwpm_gap", prior, d, r)
                if res:
                    c, sel = res
                    L.append(f"| {d} | {r} | " + " | ".join(f"{100 * c[f]:.3f}%" for f in show)
                             + f" | {sum(x['n'] for x in sel):,} |")
        L.append("")

    # --- calibration of raw q -------------------------------------------------------
    L += ["## Calibration of raw q = 1 / (1 + e^gap) (MWPM gap)", "",
          "Pooled over patches and bases; ECE over 10 equal-mass bins. Ratio = observed error / mean q; "
          "above 1 means overconfident.", "",
          "| Prior | d | r | mean q | observed error | ratio | ECE | NLL |", "|---|---|---|---|---|---|---|---|"]
    for prior in PRIORS:
        for d in (3, 5, 7):
            for r in (1, 10, 50):
                k = ("mwpm_gap", prior, d, r)
                if k in pooled:
                    q, wr = pooled[k]
                    L.append(f"| {prior} | {d} | {r} | {q.mean():.4f} | {wr.mean():.4f} | {wr.mean() / q.mean():.2f} | "
                             f"{ece(q, wr):.4f} | {nll(q, wr):.4f} |")
    L.append("")

    # --- r = 1: exact posterior vs gap ------------------------------------------------
    L += ["## r = 1: exact posterior against the MWPM gap", "",
          "Same Train shots. The exact posterior is Bayes-optimal under the DEM; the difference between the two "
          "is approximate-inference error, and the difference between priors is noise-model error.", "",
          "| d | Prior | Method | error | mean q | ECE | Brier | NLL | error at 10% discard | error at 30% discard |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for d in (3, 5):
        for prior in PRIORS:
            for method in METHODS:
                k = (method, prior, d, 1)
                res = pooled_curve(rows, method, prior, d, 1)
                if k in pooled and res:
                    q, wr = pooled[k]
                    c, _ = res
                    L.append(f"| {d} | {prior} | {NAME[method]} | {100 * wr.mean():.3f}% | {100 * q.mean():.3f}% | "
                             f"{ece(q, wr):.5f} | {brier(q, wr):.5f} | {nll(q, wr):.5f} | {100 * c[0.1]:.3f}% | {100 * c[0.3]:.3f}% |")
    L.append("")
    (RES / "m2_summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))

    # --- figures (RL prior) -------------------------------------------------------------
    plotting.apply()
    keep = [1 - f for f in DISCARD]
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.5), sharey=False)
    for ax, d in zip(axes, (3, 5, 7)):
        for i, r in enumerate((10, 30, 50)):
            res = pooled_curve(rows, "mwpm_gap", "rl", d, r)
            if res:
                c, _ = res
                ax.plot(keep, [c[f] if c[f] > 0 else np.nan for f in DISCARD], color=plotting.C[i],
                        marker=plotting.MK[i], markersize=3.5, label=f"r = {r}")
        ax.set_title(f"d = {d}")
        ax.set_yscale("log")
        ax.set_xlim(1.03, 0.27)
        ax.set_xlabel("Fraction of shots kept")
    axes[0].set_ylabel("Logical error among kept")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=3, bbox_to_anchor=(0.5, 1.1))
    fig.text(0.5, -0.1, "Train split, RL-optimized prior, MWPM gap. Points with zero errors among kept shots are not drawn.",
             ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m2_discard_curves.png")

    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.6), sharex=True, sharey=True)
    for ax, d in zip(axes, (3, 5, 7)):
        ax.plot([1e-5, 0.5], [1e-5, 0.5], color=plotting.MUTED, linewidth=0.8, linestyle="--", label="perfect calibration")
        for i, r in enumerate((10, 50)):
            k = ("mwpm_gap", "rl", d, r)
            if k in pooled:
                mq, mw, _ = reliability(*pooled[k], n_bins=10)
                ax.plot(mq, np.where(mw > 0, mw, np.nan), color=plotting.C[i], marker=plotting.MK[i], markersize=3.5, label=f"r = {r}")
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_title(f"d = {d}")
        ax.set_xlabel("Mean q in bin")
    axes[0].set_ylabel("Observed error in bin")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=3, bbox_to_anchor=(0.5, 1.1))
    fig.savefig(RES / "m2_reliability.png")

    fig, axes = plt.subplots(1, 2, figsize=(5.4, 2.5))
    for ax, d in zip(axes, (3, 5)):
        for i, method in enumerate(METHODS):
            res = pooled_curve(rows, method, "rl", d, 1)
            if res:
                c, _ = res
                ax.plot(keep, [c[f] if c[f] > 0 else np.nan for f in DISCARD], color=plotting.C[i], marker=plotting.MK[i],
                        markersize=3.5, label=NAME[method])
        ax.set_title(f"d = {d}, r = 1")
        ax.set_yscale("log")
        ax.set_xlim(1.03, 0.27)
        ax.set_xlabel("Fraction of shots kept")
    axes[0].set_ylabel("Logical error among kept")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=2, bbox_to_anchor=(0.5, 1.1))
    fig.text(0.5, -0.12, "Train split, RL-optimized prior. Points with zero errors among kept shots are not drawn.", ha="center",
             fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m2_r1_exact_vs_gap.png")
    print("wrote results/m2_summary.md, m2_train_metrics.csv and three figures")


if __name__ == "__main__":
    main()
