"""Summarise M4: calibration on Test (RQ1) and certified thresholds against uncertified rules (RQ2).

    python scripts/m4_summary.py
Reads results/m4_calibration.csv and results/m4_guarantees.csv; writes results/m4_summary.md and two figures.
"""
import collections
import csv
import pathlib

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from qeccal import plotting  # noqa: E402
from qeccal.calibration import CALIBRATORS, reliability  # noqa: E402
from qeccal.data import get_experiment, list_experiments, split_indices  # noqa: E402
from qeccal.calibration import score_from_q  # noqa: E402
from qeccal.soft.cache import load  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RES = REPO / "results"
DELTA = 0.05
RULES = ("ltt", "plugin", "naive_raw", "naive_platt")
RULE_NAME = {"ltt": "Learn-then-Test (certified)", "plugin": "Plug-in on Calibrate", "naive_raw": "Trust raw q",
             "naive_platt": "Trust Platt-calibrated q"}
CALS = ("raw", "temperature", "platt", "isotonic")
MID = (10, 30, 50)


def read(name):
    with (RES / name).open() as f:
        return list(csv.DictReader(f))


def main():
    cal = read("m4_calibration.csv")
    g = read("m4_guarantees.csv")
    for r in cal:
        for k in ("distance", "rounds", "test_n", "test_errors"):
            r[k] = int(r[k])
        for k in ("ece", "nll", "brier", "mean_q"):
            r[k] = float(r[k])
    for r in g:
        r["distance"], r["rounds"], r["alpha"] = int(r["distance"]), int(r["rounds"]), float(r["alpha"])
    n_exp = len({r["key"] for r in cal})
    size = {r["key"]: r["test_n"] for r in cal}            # Test shots per experiment
    L = ["# M4 calibration and certified thresholds (generated by scripts/m4_summary.py)", "",
         f"{n_exp} experiments (r=13 held out). Calibrators and threshold grid fitted on Train (20,000 shots), "
         "thresholds selected on Calibrate (15,000), everything below measured on Test (15,000). "
         f"delta = {DELTA}. Per-experiment rows: `results/m4_calibration.csv`, `results/m4_guarantees.csv`.", ""]

    # --- RQ1: calibration on Test ----------------------------------------------------
    L += ["## Calibration on Test (MWPM gap)", "",
          f"Mean over experiments at r in {MID}; ECE over 10 equal-mass bins, x1000. NLL in nats per shot.", "",
          "| Prior | Calibrator | ECE d=3 | ECE d=5 | ECE d=7 | NLL d=3 | NLL d=5 | NLL d=7 |", "|---|---|---|---|---|---|---|---|"]
    for prior in ("si1000", "rl"):
        for c in CALS:
            cells_e, cells_n = [], []
            for d in (3, 5, 7):
                sel = [r for r in cal if r["method"] == "mwpm_gap" and r["prior"] == prior and r["calibrator"] == c
                       and r["distance"] == d and r["rounds"] in MID]
                cells_e.append(f"{1000 * np.mean([r['ece'] for r in sel]):.2f}")
                cells_n.append(f"{np.mean([r['nll'] for r in sel]):.4f}")
            L.append(f"| {prior} | {c} | " + " | ".join(cells_e + cells_n) + " |")
    L.append("")
    temps = collections.defaultdict(list)
    for r in cal:
        if r["method"] == "mwpm_gap" and r["calibrator"] == "temperature" and r["rounds"] >= 10:
            temps[(r["prior"], r["distance"])].append(float(r["params"].split("=")[1]))
    L += ["Fitted temperature T (median over experiments with r >= 10; q = sigmoid(-gap / T), so T > 1 means "
          "the raw gap was overconfident): " + "; ".join(
              f"{p} d={d}: {np.median(v):.2f}" for (p, d), v in sorted(temps.items())), ""]
    L += ["### r = 1: MWPM gap against the exact posterior, after calibration", "",
          "| d | Prior | Method | ECE raw | ECE Platt | ECE isotonic | NLL raw | NLL Platt |", "|---|---|---|---|---|---|---|---|"]
    for d in (3, 5):
        for prior in ("si1000", "rl"):
            for m in ("mwpm_gap", "exact"):
                v = {c: [r for r in cal if r["method"] == m and r["prior"] == prior and r["calibrator"] == c
                         and r["distance"] == d and r["rounds"] == 1] for c in CALS}
                if not v["raw"]:
                    continue
                mean = lambda c, k: np.mean([r[k] for r in v[c]])  # noqa: E731
                L.append(f"| {d} | {prior} | {'Exact posterior' if m == 'exact' else 'MWPM gap'} | "
                         f"{1000 * mean('raw', 'ece'):.3f} | {1000 * mean('platt', 'ece'):.3f} | "
                         f"{1000 * mean('isotonic', 'ece'):.3f} | {mean('raw', 'nll'):.5f} | {mean('platt', 'nll'):.5f} |")
    L += ["", "ECE x1000.", ""]

    # --- RQ2: guarantees on Test -------------------------------------------------------
    alphas = sorted({r["alpha"] for r in g})
    L += ["## Abort thresholds on Test (MWPM gap, RL prior, all distances and round counts)", "",
          "Selected = the rule found a threshold (for Learn-then-Test: certified). Exceeds = Test error among kept "
          "shots is above alpha. Significant = the one-sided 95% Clopper-Pearson lower bound on the Test error is "
          "above alpha, so the excess is not Test-sample noise. Rates are over experiments with a selection.", "",
          "| alpha | Rule | Selected | Exceeds alpha | Significant | Mean kept | Mean Test error / alpha |",
          "|---|---|---|---|---|---|---|"]
    summary = {}
    for a in alphas:
        for rule in RULES:
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a and r["rule"] == rule]
            sel = [r for r in rows if r["keep"] != ""]
            ex = [int(r["exceed"]) for r in sel]
            sig = [int(r["sig_exceed"]) for r in sel]
            kept = [int(r["test_n"]) / size[r["key"]] for r in sel]
            ratio = [float(r["test_rate"]) / a for r in sel if r["test_rate"] != ""]
            summary[(a, rule)] = (len(sel) / len(rows), np.mean(ex) if ex else np.nan, np.mean(kept) if kept else np.nan)
            L.append(f"| {a:g} | {RULE_NAME[rule]} | {len(sel)}/{len(rows)} | "
                     + (f"{100 * np.mean(ex):.1f}% | {100 * np.mean(sig):.1f}% | {np.mean(kept):.2f} | {np.mean(ratio):.2f} |"
                        if sel else "- | - | - | - |"))
    L.append("")
    L += ["### Price of the certificate", "",
          "Experiments where both Learn-then-Test and the plug-in rule select a threshold: mean fraction of Test "
          "shots kept by each (the plug-in keeps more because it takes no statistical margin).", "",
          "| alpha | Experiments | Kept, Learn-then-Test | Kept, plug-in |", "|---|---|---|---|"]
    for a in alphas:
        by = {rule: {r["key"]: int(r["test_n"]) / size[r["key"]] for r in g if r["method"] == "mwpm_gap"
                     and r["prior"] == "rl" and r["alpha"] == a and r["rule"] == rule and r["keep"] != ""}
              for rule in ("ltt", "plugin")}
        both = sorted(set(by["ltt"]) & set(by["plugin"]))
        if both:
            L.append(f"| {a:g} | {len(both)} | {np.mean([by['ltt'][k] for k in both]):.2f} | "
                     f"{np.mean([by['plugin'][k] for k in both]):.2f} |")
    L.append("")
    L += ["### Learn-then-Test at alpha = 0.01 by distance and round count (RL prior)", "",
          "Certified experiments (of 2 bases x patches) and mean fraction of Test shots kept.", "",
          "| r | d=3 | d=5 | d=7 |", "|---|---|---|---|"]
    for rr in sorted({r["rounds"] for r in g}):
        cells = []
        for d in (3, 5, 7):
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == 0.01
                    and r["rule"] == "ltt" and r["distance"] == d and r["rounds"] == rr]
            sel = [r for r in rows if r["keep"] != ""]
            cells.append(f"{len(sel)}/{len(rows)}" + (f", kept {np.mean([int(r['test_n']) / size[r['key']] for r in sel]):.2f}"
                                                     if sel else ""))
        L.append(f"| {rr} | " + " | ".join(cells) + " |")
    L.append("")
    L += ["### Learn-then-Test by distance (RL prior)", "",
          "Certified experiments and mean fraction of Test shots kept at the certified threshold.", "",
          "| alpha | " + " | ".join(f"d={d} certified | d={d} kept" for d in (3, 5, 7)) + " |", "|---|" + "---|---|" * 3]
    for a in alphas:
        cells = []
        for d in (3, 5, 7):
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a
                    and r["rule"] == "ltt" and r["distance"] == d]
            sel = [r for r in rows if r["keep"] != ""]
            cells += [f"{len(sel)}/{len(rows)}", f"{np.mean([int(r['test_n']) / size[r['key']] for r in sel]):.2f}" if sel else "-"]
        L.append(f"| {a:g} | " + " | ".join(cells) + " |")
    L.append("")
    (RES / "m4_summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))

    # --- figures ------------------------------------------------------------------------
    plotting.apply()
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.7))
    ax = axes[0]
    ax.axhline(100 * DELTA, color=plotting.MUTED, linestyle="--", linewidth=0.8)
    ax.annotate("delta = 5%", (alphas[0], 100 * DELTA), xytext=(2, 3), textcoords="offset points", fontsize=7,
                color=plotting.INK2)
    for i, rule in enumerate(RULES):
        ys = [100 * summary[(a, rule)][1] for a in alphas]
        ax.plot(alphas, ys, color=plotting.C[i], marker=plotting.MK[i], markersize=3.5, label=RULE_NAME[rule])
    ax.set_xscale("log")
    ax.set_xlabel("Target alpha")
    ax.set_ylabel("Experiments exceeding alpha on Test (%)")
    ax.set_title("Does the promise hold?")
    ax = axes[1]
    styles = {3: ":", 5: "--", 7: "-"}                   # one hue (the Learn-then-Test colour); distance by line style
    for d in (3, 5, 7):
        ys = []
        for a in alphas:
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a
                    and r["rule"] == "ltt" and r["distance"] == d]
            ys.append(np.mean([int(r["test_n"]) / size[r["key"]] if r["keep"] != "" else 0.0 for r in rows]))
        ax.plot(alphas, ys, color=plotting.C[0], linestyle=styles[d], marker=plotting.MK[0], markersize=3)
        ax.annotate(f"d = {d}", (alphas[-1], ys[-1]), xytext=(4, 0), textcoords="offset points", fontsize=7,
                    color=plotting.INK2, va="center")
    ax.set_xscale("log")
    ax.set_xlim(alphas[0] / 1.6, alphas[-1] * 3.5)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Target alpha")
    ax.set_ylabel("Fraction of shots kept")
    ax.set_title("Price of the certificate (Learn-then-Test)")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=2, bbox_to_anchor=(0.5, 1.16), fontsize=7)
    fig.text(0.5, -0.1, "MWPM gap, RL-optimized prior, all distances and round counts except r=13; Test split. "
             "Right: uncertified experiments count as keeping nothing.", ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m4_guarantees.png")

    # reliability on Test before and after calibration, d = 5, r = 10, RL prior
    qs = collections.defaultdict(list)
    ws = []
    for e in list_experiments(distance=5, rounds=10):
        idx = split_indices(e)
        o = load("mwpm_gap", "rl", e.key)
        wrong = o["pred"] != e.observable_flips()
        s = o["gap"].astype(np.float64)
        for c in CALS:
            qs[c].append(CALIBRATORS[c]().fit(s[idx["train"]], wrong[idx["train"]]).predict(s[idx["test"]]))
        ws.append(wrong[idx["test"]])
    w = np.concatenate(ws)
    fig, ax = plt.subplots(figsize=(3.8, 3.0))
    ax.plot([1e-6, 0.5], [1e-6, 0.5], color=plotting.MUTED, linestyle="--", linewidth=0.8, label="perfect calibration")
    for i, c in enumerate(CALS):
        mq, mw, _ = reliability(np.concatenate(qs[c]), w, n_bins=10)
        ax.plot(mq, np.where(mw > 0, mw, np.nan), color=plotting.C[i], marker=plotting.MK[i], markersize=3.5, label=c)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Mean q in bin")
    ax.set_ylabel("Observed error in bin")
    ax.set_title("d = 5, r = 10, Test split")
    ax.legend(loc="upper left", fontsize=7)
    fig.savefig(RES / "m4_reliability_test.png")
    print("wrote results/m4_summary.md and two figures")


if __name__ == "__main__":
    main()
