"""Summarise M4: calibration on Test (RQ1) and certified thresholds against uncertified rules (RQ2).

    python scripts/m4_summary.py
Reads results/m4_calibration.csv and results/m4_guarantees.csv; writes results/m4_summary.md and two figures
(three once the belief-matching or learned-decoder caches exist).
"""
import collections
import csv
import pathlib

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from qeccal import plotting  # noqa: E402
from qeccal.calibration import CALIBRATORS, error_vs_discard, reliability  # noqa: E402
from qeccal.data import get_experiment, list_experiments, split_indices  # noqa: E402
from qeccal.calibration import score_from_q  # noqa: E402
from qeccal.soft.cache import cache_path, load  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RES = REPO / "results"
DELTA = 0.05
RULES = ("ltt", "plugin", "naive_raw", "naive_platt")
RULE_NAME = {"ltt": "Learn-then-Test (certified)", "plugin": "Plug-in on Calibrate", "naive_raw": "Trust raw q",
             "naive_platt": "Trust Platt-calibrated q"}
CALS = ("raw", "temperature", "platt", "isotonic")
MID = (10, 30, 50)


def read(name):
    with (RES / name).open() as f:
        return list(csv.DictReader(f))


def main():
    cal = read("m4_calibration.csv")
    g = read("m4_guarantees.csv")
    for r in cal:
        for k in ("distance", "rounds", "test_n", "test_errors"):
            r[k] = int(r[k])
        for k in ("ece", "nll", "brier", "mean_q"):
            r[k] = float(r[k])
    for r in g:
        r["distance"], r["rounds"], r["alpha"] = int(r["distance"]), int(r["rounds"]), float(r["alpha"])
    n_exp = len({r["key"] for r in cal})
    size = {r["key"]: r["test_n"] for r in cal}            # Test shots per experiment
    L = ["# M4 calibration and certified thresholds (generated by scripts/m4_summary.py)", "",
         f"{n_exp} experiments (r=13 held out). Calibrators and threshold grid fitted on Train (20,000 shots), "
         "thresholds selected on Calibrate (15,000), everything below measured on Test (15,000). "
         f"delta = {DELTA}. Per-experiment rows: `results/m4_calibration.csv`, `results/m4_guarantees.csv`.", ""]

    # --- RQ1: calibration on Test ----------------------------------------------------
    L += ["## Calibration on Test (MWPM gap)", "",
          f"Mean over experiments at r in {MID}; ECE over 10 equal-mass bins, x1000. NLL in nats per shot.", "",
          "| Prior | Calibrator | ECE d=3 | ECE d=5 | ECE d=7 | NLL d=3 | NLL d=5 | NLL d=7 |", "|---|---|---|---|---|---|---|---|"]
    for prior in ("si1000", "rl"):
        for c in CALS:
            cells_e, cells_n = [], []
            for d in (3, 5, 7):
                sel = [r for r in cal if r["method"] == "mwpm_gap" and r["prior"] == prior and r["calibrator"] == c
                       and r["distance"] == d and r["rounds"] in MID]
                cells_e.append(f"{1000 * np.mean([r['ece'] for r in sel]):.2f}")
                cells_n.append(f"{np.mean([r['nll'] for r in sel]):.4f}")
            L.append(f"| {prior} | {c} | " + " | ".join(cells_e + cells_n) + " |")
    L.append("")
    temps = collections.defaultdict(list)
    for r in cal:
        if r["method"] == "mwpm_gap" and r["calibrator"] == "temperature" and r["rounds"] >= 10:
            temps[(r["prior"], r["distance"])].append(float(r["params"].split("=")[1]))
    L += ["Fitted temperature T (median over experiments with r >= 10; q = sigmoid(-gap / T), so T > 1 means "
          "the raw gap was overconfident): " + "; ".join(
              f"{p} d={d}: {np.median(v):.2f}" for (p, d), v in sorted(temps.items())), ""]
    L += ["### r = 1: MWPM gap against the exact posterior, after calibration", "",
          "| d | Prior | Method | ECE raw | ECE Platt | ECE isotonic | NLL raw | NLL Platt |", "|---|---|---|---|---|---|---|---|"]
    for d in (3, 5):
        for prior in ("si1000", "rl"):
            for m in ("mwpm_gap", "exact"):
                v = {c: [r for r in cal if r["method"] == m and r["prior"] == prior and r["calibrator"] == c
                         and r["distance"] == d and r["rounds"] == 1] for c in CALS}
                if not v["raw"]:
                    continue
                mean = lambda c, k: np.mean([r[k] for r in v[c]])  # noqa: E731
                L.append(f"| {d} | {prior} | {'Exact posterior' if m == 'exact' else 'MWPM gap'} | "
                         f"{1000 * mean('raw', 'ece'):.3f} | {1000 * mean('platt', 'ece'):.3f} | "
                         f"{1000 * mean('isotonic', 'ece'):.3f} | {mean('raw', 'nll'):.5f} | {mean('platt', 'nll'):.5f} |")
    L += ["", "ECE x1000.", ""]

    # --- RQ2: guarantees on Test -------------------------------------------------------
    alphas = sorted({r["alpha"] for r in g})
    L += ["## Abort thresholds on Test (MWPM gap, RL prior, all distances and round counts)", "",
          "Selected = the rule found a threshold (for Learn-then-Test: certified). Exceeds = Test error among kept "
          "shots is above alpha. Significant = the one-sided 95% Clopper-Pearson lower bound on the Test error is "
          "above alpha, so the excess is not Test-sample noise. Rates are over experiments with a selection.", "",
          "| alpha | Rule | Selected | Exceeds alpha | Significant | Mean kept | Mean Test error / alpha |",
          "|---|---|---|---|---|---|---|"]
    summary = {}
    for a in alphas:
        for rule in RULES:
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a and r["rule"] == rule]
            sel = [r for r in rows if r["keep"] != ""]
            ex = [int(r["exceed"]) for r in sel]
            sig = [int(r["sig_exceed"]) for r in sel]
            kept = [int(r["test_n"]) / size[r["key"]] for r in sel]
            ratio = [float(r["test_rate"]) / a for r in sel if r["test_rate"] != ""]
            summary[(a, rule)] = (len(sel) / len(rows), np.mean(ex) if ex else np.nan, np.mean(kept) if kept else np.nan)
            L.append(f"| {a:g} | {RULE_NAME[rule]} | {len(sel)}/{len(rows)} | "
                     + (f"{100 * np.mean(ex):.1f}% | {100 * np.mean(sig):.1f}% | {np.mean(kept):.2f} | {np.mean(ratio):.2f} |"
                        if sel else "- | - | - | - |"))
    L.append("")
    L += ["### Price of the certificate", "",
          "Experiments where both Learn-then-Test and the plug-in rule select a threshold: mean fraction of Test "
          "shots kept by each (the plug-in keeps more because it takes no statistical margin).", "",
          "| alpha | Experiments | Kept, Learn-then-Test | Kept, plug-in |", "|---|---|---|---|"]
    for a in alphas:
        by = {rule: {r["key"]: int(r["test_n"]) / size[r["key"]] for r in g if r["method"] == "mwpm_gap"
                     and r["prior"] == "rl" and r["alpha"] == a and r["rule"] == rule and r["keep"] != ""}
              for rule in ("ltt", "plugin")}
        both = sorted(set(by["ltt"]) & set(by["plugin"]))
        if both:
            L.append(f"| {a:g} | {len(both)} | {np.mean([by['ltt'][k] for k in both]):.2f} | "
                     f"{np.mean([by['plugin'][k] for k in both]):.2f} |")
    L.append("")
    L += ["### Learn-then-Test at alpha = 0.01 by distance and round count (RL prior)", "",
          "Certified experiments (of 2 bases x patches) and mean fraction of Test shots kept.", "",
          "| r | d=3 | d=5 | d=7 |", "|---|---|---|---|"]
    for rr in sorted({r["rounds"] for r in g}):
        cells = []
        for d in (3, 5, 7):
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == 0.01
                    and r["rule"] == "ltt" and r["distance"] == d and r["rounds"] == rr]
            sel = [r for r in rows if r["keep"] != ""]
            cells.append(f"{len(sel)}/{len(rows)}" + (f", kept {np.mean([int(r['test_n']) / size[r['key']] for r in sel]):.2f}"
                                                     if sel else ""))
        L.append(f"| {rr} | " + " | ".join(cells) + " |")
    L.append("")
    L += ["### Learn-then-Test by distance (RL prior)", "",
          "Certified experiments and mean fraction of Test shots kept at the certified threshold.", "",
          "| alpha | " + " | ".join(f"d={d} certified | d={d} kept" for d in (3, 5, 7)) + " |", "|---|" + "---|---|" * 3]
    for a in alphas:
        cells = []
        for d in (3, 5, 7):
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a
                    and r["rule"] == "ltt" and r["distance"] == d]
            sel = [r for r in rows if r["keep"] != ""]
            cells += [f"{len(sel)}/{len(rows)}", f"{np.mean([int(r['test_n']) / size[r['key']] for r in sel]):.2f}" if sel else "-"]
        L.append(f"| {a:g} | " + " | ".join(cells) + " |")
    L.append("")
    others = [m for m in ("bm_gap", "nn") if any(r["method"] == m for r in cal)]
    for m in others:
        L += other_section(cal, g, m, alphas, size)
    (RES / "m4_summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))

    # --- figures ------------------------------------------------------------------------
    plotting.apply()
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.7))
    ax = axes[0]
    ax.axhline(100 * DELTA, color=plotting.MUTED, linestyle="--", linewidth=0.8)
    ax.annotate("delta = 5%", (alphas[0], 100 * DELTA), xytext=(2, 3), textcoords="offset points", fontsize=7,
                color=plotting.INK2)
    for i, rule in enumerate(RULES):
        ys = [100 * summary[(a, rule)][1] for a in alphas]
        ax.plot(alphas, ys, color=plotting.C[i], marker=plotting.MK[i], markersize=3.5, label=RULE_NAME[rule])
    ax.set_xscale("log")
    ax.set_xlabel("Target alpha")
    ax.set_ylabel("Experiments exceeding alpha on Test (%)")
    ax.set_title("Does the promise hold?")
    ax = axes[1]
    styles = {3: ":", 5: "--", 7: "-"}                   # one hue (the Learn-then-Test colour); distance by line style
    for d in (3, 5, 7):
        ys = []
        for a in alphas:
            rows = [r for r in g if r["method"] == "mwpm_gap" and r["prior"] == "rl" and r["alpha"] == a
                    and r["rule"] == "ltt" and r["distance"] == d]
            ys.append(np.mean([int(r["test_n"]) / size[r["key"]] if r["keep"] != "" else 0.0 for r in rows]))
        ax.plot(alphas, ys, color=plotting.C[0], linestyle=styles[d], marker=plotting.MK[0], markersize=3)
        ax.annotate(f"d = {d}", (alphas[-1], ys[-1]), xytext=(4, 0), textcoords="offset points", fontsize=7,
                    color=plotting.INK2, va="center")
    ax.set_xscale("log")
    ax.set_xlim(alphas[0] / 1.6, alphas[-1] * 3.5)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Target alpha")
    ax.set_ylabel("Fraction of shots kept")
    ax.set_title("Price of the certificate (Learn-then-Test)")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=2, bbox_to_anchor=(0.5, 1.16), fontsize=7)
    fig.text(0.5, -0.1, "MWPM gap, RL-optimized prior, all distances and round counts except r=13; Test split. "
             "Right: uncertified experiments count as keeping nothing.", ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m4_guarantees.png")

    # reliability on Test before and after calibration, d = 5, r = 10, RL prior
    qs = collections.defaultdict(list)
    ws = []
    for e in list_experiments(distance=5, rounds=10):
        idx = split_indices(e)
        o = load("mwpm_gap", "rl", e.key)
        wrong = o["pred"] != e.observable_flips()
        s = o["gap"].astype(np.float64)
        for c in CALS:
            qs[c].append(CALIBRATORS[c]().fit(s[idx["train"]], wrong[idx["train"]]).predict(s[idx["test"]]))
        ws.append(wrong[idx["test"]])
    w = np.concatenate(ws)
    fig, ax = plt.subplots(figsize=(3.8, 3.0))
    ax.plot([1e-6, 0.5], [1e-6, 0.5], color=plotting.MUTED, linestyle="--", linewidth=0.8, label="perfect calibration")
    for i, c in enumerate(CALS):
        mq, mw, _ = reliability(np.concatenate(qs[c]), w, n_bins=10)
        ax.plot(mq, np.where(mw > 0, mw, np.nan), color=plotting.C[i], marker=plotting.MK[i], markersize=3.5, label=c)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Mean q in bin")
    ax.set_ylabel("Observed error in bin")
    ax.set_title("d = 5, r = 10, Test split")
    ax.legend(loc="upper left", fontsize=7)
    fig.savefig(RES / "m4_reliability_test.png")
    if others:
        scores_figure()
    print("wrote results/m4_summary.md and figures")


NAME = {"mwpm_gap": "MWPM gap", "bm_gap": "Belief-matching gap", "nn": "Learned decoder"}
SHORT = {"mwpm_gap": "MWPM", "bm_gap": "BM", "nn": "NN"}


def other_section(cal, g, method, alphas, size):
    """One extra score against the MWPM gap, on the experiments the extra score was run on (RL prior)."""
    keys = {r["key"] for r in cal if r["method"] == method}
    rounds = sorted({r["rounds"] for r in cal if r["key"] in keys})
    dists = sorted({r["distance"] for r in cal if r["key"] in keys})
    ms = ("mwpm_gap", method)
    a, b = SHORT["mwpm_gap"], SHORT[method]
    note = {"bm_gap": "", "nn": " The learned decoder's calibrators and thresholds use the 5,000 Train shots it "
            "was not fine-tuned on; the MWPM gap uses all 20,000."}[method]
    L = [f"## {NAME[method]} against the MWPM gap (RL prior, Test split)", "",
         f"{len(keys)} experiments (d in {dists}, r in {rounds}, all patches and bases). Logical error: pooled over "
         "patches and bases. ECE x1000 and NLL (nats per shot): means over experiments. Each score is calibrated "
         "on its own Train split." + note, "",
         f"| d | r | Error, {a} | Error, {b} | ECE raw, {a} | ECE raw, {b} | ECE Platt, {a} | ECE Platt, {b} "
         f"| NLL Platt, {a} | NLL Platt, {b} |", "|---|---|---|---|---|---|---|---|---|---|"]
    pick = lambda m, c, d, rr: [r for r in cal if r["method"] == m and r["prior"] == "rl" and r["calibrator"] == c  # noqa: E731
                                and r["distance"] == d and r["rounds"] == rr and r["key"] in keys]
    for d in dists:
        for rr in rounds:
            raw = {m: pick(m, "raw", d, rr) for m in ms}
            if not raw[method]:
                continue
            platt = {m: pick(m, "platt", d, rr) for m in ms}
            err = [sum(r["test_errors"] for r in raw[m]) / sum(r["test_n"] for r in raw[m]) for m in ms]
            L.append(f"| {d} | {rr} | {100 * err[0]:.3f}% | {100 * err[1]:.3f}% | "
                     + " | ".join(f"{1000 * np.mean([r['ece'] for r in raw[m]]):.2f}" for m in ms) + " | "
                     + " | ".join(f"{1000 * np.mean([r['ece'] for r in platt[m]]):.2f}" for m in ms) + " | "
                     + " | ".join(f"{np.mean([r['nll'] for r in platt[m]]):.4f}" for m in ms) + " |")
    L += ["", "Learn-then-Test on the same experiments: certified experiments, mean fraction of Test shots kept "
          "(uncertified count as 0), and significant exceedance among certified.", "",
          f"| alpha | Certified, {a} | Certified, {b} | Kept, {a} | Kept, {b} | Significant, {a} | Significant, {b} |",
          "|---|---|---|---|---|---|---|"]
    for al in alphas:
        rows = {m: [r for r in g if r["method"] == m and r["prior"] == "rl" and r["alpha"] == al and r["rule"] == "ltt"
                    and r["key"] in keys] for m in ms}
        sel = {m: [r for r in v if r["keep"] != ""] for m, v in rows.items()}
        kept = {m: np.mean([int(r["test_n"]) / size[r["key"]] if r["keep"] != "" else 0.0 for r in v]) for m, v in rows.items()}
        sig = {m: f"{100 * np.mean([int(r['sig_exceed']) for r in v]):.1f}%" if v else "-" for m, v in sel.items()}
        L.append(f"| {al:g} | {len(sel[ms[0]])}/{len(rows[ms[0]])} | {len(sel[ms[1]])}/{len(rows[ms[1]])} | "
                 f"{kept[ms[0]]:.2f} | {kept[ms[1]]:.2f} | {sig[ms[0]]} | {sig[ms[1]]} |")
    L.append("")
    return L


def scores_figure():
    """Error among kept Test shots against fraction kept, r = 10, pooled over patches and bases, per distance."""
    fracs = np.linspace(0, 0.95, 39)
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.5))
    for ax, d in zip(axes, (3, 5, 7)):
        exps = list_experiments(distance=d, rounds=10)
        for i, m in enumerate(("mwpm_gap", "bm_gap", "nn")):
            have = [e for e in exps if cache_path(m, "rl", e.key).exists()]
            if not have:
                continue
            s_all, w_all = [], []
            for e in have:
                o = load(m, "rl", e.key)
                te = split_indices(e)["test"]
                s = o["gap"].astype(np.float64) if "gap" in o else score_from_q(o["q"])
                s_all.append(s[te])
                w_all.append((o["pred"] != e.observable_flips())[te])
            s, w = np.concatenate(s_all), np.concatenate(w_all)
            kept, err = error_vs_discard(-s, w, fracs, np.random.default_rng(0))
            ax.plot(kept / s.size, np.where(err > 0, err / kept, np.nan), color=plotting.C[i], label=NAME[m])
        ax.set_yscale("log")
        ax.set_xlim(1.02, 0.0)
        ax.set_xlabel("Fraction of shots kept")
        ax.set_title(f"d = {d}, r = 10", fontsize=8)
    axes[0].set_ylabel("Logical error among kept")
    handles = {}
    for ax in axes:
        for h, lab in zip(*ax.get_legend_handles_labels()):
            handles.setdefault(lab, h)
    fig.legend(handles.values(), handles.keys(), loc="upper center", ncol=3, bbox_to_anchor=(0.5, 1.1), fontsize=7)
    fig.text(0.5, -0.1, "RL prior, Test split, pooled over patches and bases; least confident shots discarded first. "
             "The learned decoder was trained at d = 3 only.", ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m4_scores_vs_mwpm.png")

if __name__ == "__main__":
    main()
