"""Summarise M5 / RQ3: how often a certified threshold, moved from source to target, breaks its promise.

    python scripts/m5_summary.py
Reads results/m5_drift.csv and results/m5_calibration.csv; writes results/m5_summary.md and three figures.
"""
import collections
import csv
import pathlib

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.colors import LinearSegmentedColormap, TwoSlopeNorm  # noqa: E402

from qeccal import plotting  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RES = REPO / "results"
DELTA = 0.05
AXES = ("same", "patch", "basis", "pooled", "sim")
AXIS_NAME = {"same": "Same experiment (reference)", "patch": "Other patch", "basis": "Other basis",
             "pooled": "Other patches pooled", "sim": "Simulation from the DEM"}


def read(name):
    with (RES / name).open() as f:
        return list(csv.DictReader(f))


def cell(rows):
    """'significant / exceed (certified/pairs)' over certified pairs; None if nothing is certified."""
    cert = [r for r in rows if r["certified"]]
    if not cert:
        return None, f"- (0/{len(rows)})"
    ex = np.mean([int(r["exceed"]) for r in cert])
    sig = np.mean([int(r["sig_exceed"]) for r in cert])
    return (ex, sig), f"{100 * sig:.0f}% / {100 * ex:.0f}% ({len(cert)}/{len(rows)})"


def main():
    g_all = read("m5_drift.csv")
    c_all = read("m5_calibration.csv")
    for r in g_all:
        r["alpha"], r["distance"], r["rounds"], r["certified"] = float(r["alpha"]), int(r["distance"]), int(r["rounds"]), int(r["certified"])
    for r in c_all:
        r["distance"], r["rounds"], r["ece"], r["nll"] = int(r["distance"]), int(r["rounds"]), float(r["ece"]), float(r["nll"])
    g = [r for r in g_all if r["method"] == "mwpm_gap" and r["transfer"] == "threshold"]   # the main study
    c = [r for r in c_all if r["method"] == "mwpm_gap"]
    alphas = sorted({r["alpha"] for r in g})
    L = ["# M5 drift study, RQ3 (generated by scripts/m5_summary.py)", "",
         "Score: MWPM gap. Calibrators fitted on the source Train split, threshold certified by Learn-then-Test on the "
         f"source Calibrate split (delta = {DELTA}), measured on the target Test split. Round counts 1, 10, 30, 50. "
         "Per-pair rows: `results/m5_drift.csv`, `results/m5_calibration.csv`.", ""]

    stats = {}
    for prior in ("rl", "si1000"):
        L += [f"## Does the certificate transfer? Prior: {'RL-optimized' if prior == 'rl' else 'SI1000'}", "",
              "Each cell: significant exceedance / exceedance, over certified source-target pairs (certified pairs "
              "in brackets). Exceedance = target Test error among kept shots above alpha; significant = its one-sided "
              "95% Clopper-Pearson lower bound is above alpha. In-distribution, the guarantee allows at most delta = 5% "
              "of true exceedances. \"kept none\": the source threshold keeps no target Test shot (counted as no exceedance).", "",
              "| Shift | " + " | ".join(f"alpha={a:g}" for a in alphas) + " |", "|---|" + "---|" * len(alphas)]
        for axis in AXES:
            cells = []
            for a in alphas:
                rows = [r for r in g if r["prior"] == prior and r["axis"] == axis and r["alpha"] == a]
                cert = [r for r in rows if r["certified"]]
                if not cert:
                    cells.append(f"- (0/{len(rows)})")
                    continue
                ex = np.mean([int(r["exceed"]) for r in cert])
                sig = np.mean([int(r["sig_exceed"]) for r in cert])
                kept_some = [r for r in cert if int(r["test_n"]) > 0]
                ratio = np.mean([float(r["test_rate"]) / a for r in kept_some]) if kept_some else np.nan
                empty = len(cert) - len(kept_some)
                stats[(prior, axis, a)] = (ex, sig, ratio, len(cert))
                cells.append(f"{100 * sig:.0f}% / {100 * ex:.0f}% ({len(cert)}/{len(rows)})" + (f", {empty} kept none" if empty else ""))
            L.append(f"| {AXIS_NAME[axis]} | " + " | ".join(cells) + " |")
        L += ["", "Mean target Test error / alpha over certified pairs that keep at least one target shot:", "",
              "| Shift | " + " | ".join(f"alpha={a:g}" for a in alphas) + " |", "|---|" + "---|" * len(alphas)]
        for axis in AXES:
            L.append(f"| {AXIS_NAME[axis]} | " + " | ".join(
                f"{stats[(prior, axis, a)][2]:.2f}" if (prior, axis, a) in stats else "-" for a in alphas) + " |")
        L.append("")

    # calibration transfer
    L += ["## Does a fitted calibrator transfer? (target Test ECE x1000, mean over pairs, r in 10, 30, 50)", "",
          "| Prior | Shift | Platt d=3 | Platt d=5 | Platt d=7 | isotonic d=3 | isotonic d=5 | isotonic d=7 |",
          "|---|---|---|---|---|---|---|---|"]
    for prior in ("rl", "si1000"):
        for axis in AXES:
            cells = []
            for cal in ("platt", "isotonic"):
                for d in (3, 5, 7):
                    v = [r["ece"] for r in c if r["prior"] == prior and r["axis"] == axis and r["calibrator"] == cal
                         and r["distance"] == d and r["rounds"] in (10, 30, 50)]
                    cells.append(f"{1000 * np.mean(v):.1f}" if v else "-")
            L.append(f"| {prior} | {AXIS_NAME[axis]} | " + " | ".join(cells) + " |")
    L.append("")

    # which targets break under patch transfer (RL, alpha = 0.01, r = 10)
    L += ["## Patch transfer at alpha = 0.01, r = 10 (RL prior): targets that break", "",
          "For each target, how many of the other patches' certified thresholds significantly exceed alpha on it.", "",
          "| d | Basis | Target patch | Sources certified | Significant exceedances | Worst Test error / alpha |",
          "|---|---|---|---|---|---|"]
    tgt = collections.defaultdict(list)
    for r in g:
        if r["prior"] == "rl" and r["axis"] == "patch" and r["alpha"] == 0.01 and r["rounds"] == 10 and r["certified"]:
            tgt[(r["distance"], r["basis"], r["patch"])].append(r)
    for (d, b, p), rows in sorted(tgt.items()):
        sig = sum(int(r["sig_exceed"]) for r in rows)
        worst = max(float(r["test_rate"]) / 0.01 for r in rows)
        L.append(f"| {d} | {b} | {p} | {len(rows)} | {sig} | {worst:.2f} |")
    L.append("")
    L += ["Seen from the source side (same rows): how many targets each source patch's certified threshold breaks.", "",
          "| d | Basis | Source patch | Targets | Significant exceedances | Keep fraction certified on source |",
          "|---|---|---|---|---|---|"]
    src = collections.defaultdict(list)
    for rows in tgt.values():
        for r in rows:
            src[(r["distance"], r["basis"], r["source"].split("_at_")[1].split("/")[0])].append(r)
    for (d, b, p), rows in sorted(src.items()):
        L.append(f"| {d} | {b} | {p} | {len(rows)} | {sum(int(r['sig_exceed']) for r in rows)} | {rows[0]['keep']} |")
    L.append("")
    # keep-fraction transfer against threshold transfer
    L += ["## Transferring the keep fraction instead of the threshold (MWPM gap)", "",
          "Threshold: the source's gap threshold is used as is on the target. Keep fraction: the target keeps the same "
          "fraction of its own shots as was certified on the source (threshold re-set at the quantile of the target's "
          "unlabelled Train scores). Cells as above: significant / exceedance (certified / pairs).", "",
          "| Prior | Shift | Transfer | " + " | ".join(f"alpha={a:g}" for a in alphas) + " |",
          "|---|---|---|" + "---|" * len(alphas)]
    kf = {}
    for prior in ("rl", "si1000"):
        for axis in ("patch", "basis", "pooled", "sim"):
            for transfer in ("threshold", "keep_fraction"):
                cells = []
                for a in alphas:
                    v, txt = cell([r for r in g_all if r["method"] == "mwpm_gap" and r["prior"] == prior
                                   and r["axis"] == axis and r["transfer"] == transfer and r["alpha"] == a])
                    if v:
                        kf[(prior, axis, transfer, a)] = v
                    cells.append(txt)
                L.append(f"| {prior} | {AXIS_NAME[axis]} | {transfer.replace('_', ' ')} | " + " | ".join(cells) + " |")
    L.append("")

    # the other scores against the MWPM gap under shift, on the targets each one covers
    name = {"bm_gap": "Belief-matching gap", "nn": "Learned decoder (d = 3)"}
    for method in ("bm_gap", "nn"):
        rows_m = [r for r in g_all if r["method"] == method and r["transfer"] == "threshold"]
        if not rows_m:
            continue
        targets = {r["target"] for r in rows_m}
        L += [f"## {name[method]} under shift (RL prior, threshold transfer)", "",
              f"Same study with the {name[method].lower()} as the score, hardware axes only, on the {len(targets)} "
              "target experiments it covers; the MWPM rows are restricted to the same targets. Cells: significant / "
              "exceedance (certified / pairs).", "",
              "| Shift | Score | " + " | ".join(f"alpha={a:g}" for a in alphas) + " |", "|---|---|" + "---|" * len(alphas)]
        for axis in ("same", "patch", "basis", "pooled"):
            for m, label in (("mwpm_gap", "MWPM gap"), (method, name[method])):
                cells = [cell([r for r in g_all if r["method"] == m and r["prior"] == "rl" and r["axis"] == axis
                               and r["transfer"] == "threshold" and r["alpha"] == a and r["target"] in targets])[1]
                         for a in alphas]
                L.append(f"| {AXIS_NAME[axis]} | {label} | " + " | ".join(cells) + " |")
        L.append("")
    (RES / "m5_summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))

    # --- figure 1: exceedance by shift axis (RL prior) -----------------------------------
    plotting.apply()
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.8), sharey=True)
    for ax in axes:
        ax.axhline(100 * DELTA, color=plotting.MUTED, linestyle="--", linewidth=0.8)
        ax.set_xscale("log")
        ax.set_xlabel("Target alpha")
    ax = axes[0]
    for i, axis in enumerate(("same", "patch", "basis", "pooled")):
        xs = [a for a in alphas if ("rl", axis, a) in stats]
        ax.plot(xs, [100 * stats[("rl", axis, a)][0] for a in xs], color=plotting.C[i], marker=plotting.MK[i],
                markersize=3.5, label=AXIS_NAME[axis])
    ax.set_ylabel("Certified pairs exceeding alpha on target Test (%)")
    ax.set_title("Hardware to hardware (RL prior)")
    ax.legend(loc="upper left", fontsize=6.5)
    ax = axes[1]
    series = [("rl", "same", plotting.C[0], "-", "same experiment"),
              ("rl", "sim", plotting.INK2, "-", "simulated, RL DEM"),
              ("si1000", "sim", plotting.INK2, "--", "simulated, SI1000 DEM")]
    for prior, axis, col, ls, name in series:
        xs = [a for a in alphas if (prior, axis, a) in stats]
        ys = [100 * stats[(prior, axis, a)][0] for a in xs]
        ax.plot(xs, ys, color=col, linestyle=ls, marker="o", markersize=3)
        ax.annotate(name, (xs[-1], ys[-1]), xytext=(5, 0), textcoords="offset points", fontsize=6.5,
                    color=plotting.INK2, va="center")
    ax.set_xlim(alphas[0] / 1.5, alphas[-1] * 12)
    ax.set_xticks([a for a in (1e-4, 1e-3, 1e-2, 1e-1) if alphas[0] <= a <= alphas[-1]])
    ax.set_title("Simulation to hardware")
    fig.text(0.5, -0.08, "Dashed grey line: delta = 5%. Round counts 1, 10, 30, 50; MWPM gap; target Test split.",
             ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m5_transfer.png")

    # --- figure 2: patch-to-patch matrix, d = 3, r = 10, alpha = 0.01, RL prior ----------------
    cmap = LinearSegmentedColormap.from_list("div", [plotting.C[0], "#f2f1ec", plotting.C[1]])
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.4))
    for ax, basis in zip(axes, ("X", "Z")):
        rows = [r for r in g if r["prior"] == "rl" and r["alpha"] == 0.01 and r["rounds"] == 10 and r["distance"] == 3
                and r["basis"] == basis and r["axis"] in ("patch", "same")]
        patches = sorted({r["patch"] for r in rows}, key=lambda p: tuple(int(x) for x in p[1:].split("_")))
        M = np.full((len(patches), len(patches)), np.nan)
        for r in rows:
            if r["certified"] and r["test_rate"] != "":
                src = r["patch"] if r["axis"] == "same" else r["source"].split("_at_")[1].split("/")[0]
                M[patches.index(src), patches.index(r["patch"])] = np.log10(max(float(r["test_rate"]), 1e-4) / 0.01)
        im = ax.imshow(M, cmap=cmap, norm=TwoSlopeNorm(vcenter=0, vmin=-1, vmax=1))
        for i in range(len(patches)):
            for j in range(len(patches)):
                if np.isfinite(M[i, j]):
                    ax.text(j, i, f"{10 ** M[i, j]:.1f}", ha="center", va="center", fontsize=5.5, color=plotting.INK)
        ax.set_xticks(range(len(patches)), patches, rotation=90, fontsize=6.5)
        ax.set_yticks(range(len(patches)), patches, fontsize=6.5)
        ax.set_xlabel("Target patch (Test)")
        ax.set_title(f"d = 3, r = 10, basis {basis}")
        ax.grid(False)
    axes[0].set_ylabel("Source patch (certified on)")
    cb = fig.colorbar(im, ax=axes, shrink=0.8, ticks=[-1, 0, 1])
    cb.ax.set_yticklabels(["0.1", "1", "10"])
    cb.set_label("Target Test error / alpha")
    fig.text(0.45, -0.04, "alpha = 0.01, RL prior. Diagonal: same experiment. Above 1 (orange) = the promise failed on that target.",
             ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m5_patch_matrix.png")

    # --- figure 3: threshold transfer against keep-fraction transfer ------------------------
    panels = [("rl", "patch", "Other patch"), ("rl", "pooled", "Other patches pooled"),
              ("rl", "sim", "RL DEM sim to hardware"), ("si1000", "sim", "SI1000 sim to hardware")]
    fig, axes = plt.subplots(1, len(panels), figsize=(8.8, 2.6), sharey=True)
    for ax, (prior, axis, title) in zip(axes, panels):
        ax.axhline(100 * DELTA, color=plotting.MUTED, linestyle="--", linewidth=0.8)
        for i, (transfer, name) in enumerate((("threshold", "same threshold"), ("keep_fraction", "same keep fraction"))):
            xs = [a for a in alphas if (prior, axis, transfer, a) in kf]
            ax.plot(xs, [100 * kf[(prior, axis, transfer, a)][0] for a in xs], color=plotting.C[i],
                    marker=plotting.MK[i], markersize=3, label=name)
        ax.set_xscale("log")
        ax.set_xlabel("Target alpha")
        ax.set_title(title, fontsize=8)
    axes[0].set_ylabel("Certified pairs exceeding alpha (%)")
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=2, bbox_to_anchor=(0.5, 1.1), fontsize=7)
    fig.text(0.5, -0.1, "MWPM gap, RL prior unless stated; target Test split; dashed grey line: delta = 5%. "
             "Where the lines coincide, both transfers gave the same result.", ha="center", fontsize=7, color=plotting.INK2)
    fig.savefig(RES / "m5_keep_fraction.png")
    print("wrote results/m5_summary.md and three figures")


if __name__ == "__main__":
    main()
